# Generated by Django 5.0.6 on 2024-06-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_memberclient_alter_sportevent_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportevent',
            old_name='clients',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='date',
        ),
    ]
