# Generated by Django 5.0.6 on 2024-06-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_clients_sportevent_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberclient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/'),
        ),
    ]
